apiVersion: v1
kind: ServiceAccount
metadata:
  name: fitness-app-sa
  namespace: default
  annotations:
    # This Client ID tells Workload Identity which Azure Identity to assume
    # Replace the value below with the Client ID(managed identity)
    azure.workload.identity/client-id: "c2c83e4b-6303-41d0-bc6e-f568168c9433"
  labels:
    azure.workload.identity/use: "true"
