apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv-fitness-app
  namespace: default
spec:
  provider: azure
  secretObjects:
  # This section creates a regular Kubernetes Secret from the Key Vault data
  # so that the Pod can load it into environment variables easily.
  - secretName: fitness-app-env-secret
    type: Opaque
    data:
    # 'objectName' must match the secret name in Key Vault
    # 'key' will be the name of the environment variable in Kubernetes
    - objectName: CosmosDb
      key: MONGODB_URI
    - objectName: JwtSecret
      key: JWT_SECRET
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: "c2c83e4b-6303-41d0-bc6e-f568168c9433" # Replace with your Client ID
    keyvaultName: "fitness-kv16" # Replace with your Key Vault name
    tenantId: "bf93bb5e-ecf0-4e3d-be0e-79b5cc527a48" # You can get this by running: az account show --query tenantId -otsv
    objects: |
      array:
        - |
          objectName: CosmosDb
          objectType: secret
          objectVersion: ""
        - |
          objectName: JwtSecret
          objectType: secret
          objectVersion: ""
